apiVersion: v1
kind: Secret
metadata:
  name: grafana-logaccess
type: Opaque
data:
  #Base64 encoded username and password for Grafana
  #can be encoded using the following command:
  # echo -n 'admin' | base64
  username: YWRtaW4=
  # echo -n 'whatevergrafanapassword' | base64
  password: d2hhdGV2ZXJncmFmYW5hcGFzc3dvcmQ=