# Default values for hpcc-localfile.

# NB: hostpath and 'subPath's must exist on host
common:
  #The host path provides the location on the host machine that will contain the data.
  hostpath: "/run/desktop/mnt/host/c/hpccdata"
  mountPrefix: "/var/lib/HPCCSystems"

planes:
- name: dali
  subPath: dalistorage
  size: 1Gi
  category: dali
- name: dll
  subPath: queries # cannot currently be changed
  size: 1Gi
  category: dll
  rwmany: true
- name: sasha
  subPath: sasha
  size: 1Gi
  rwmany: true
  category: sasha
- name: debug
  subPath: debug
  size: 5Gi
  rwmany: true
  category: debug
- name: data
  subPath: hpcc-data # cannot currently be changed
  size: 3Gi
  category: data # NB: all "data" planes will be auto mounted by engine components and others that require access to data
  rwmany: true
- name: mydropzone
  subPath: dropzone
  size: 1Gi
  rwmany: true
  category: lz

