application:
  name: eclwatch
  services:
   - WsSMC
   - WsWorkunits
   - WsTopology
   - WsDfu
   - WsDfuXRef
   - WsFileIO
   - WsPackageProcess
   - FileSpray
   - ws_machine
   - ws_elk
   - ws_access
   - ws_account
   - ws_esdlconfig
   - ws_store
   - ws_codesign
