# Overrides for http-connect secrets in hpcc.
# NB: The "hpcc-connect-testsecret" should be created before installing the helm chart.

secrets:
  ecl:
    http-connect-urlsecret: "http-connect-urlsecret"
    http-connect-basicsecret: "http-connect-basicsecret"
    http-connect-certsecret: "http-connect-certsecret"
