name: Run helm chart tests

on:
  push:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"
    paths:
      - "helm/**/*"
      - "testing/helm/**/*"
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"
    paths:
      - "helm/**/*"
      - "testing/helm/**/*"

jobs:
  build:
    name: "Check helm chart lint"
    runs-on: ubuntu-latest
    if: github.repository == 'hpcc-systems/HPCC-Platform'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: azure/setup-helm@v1
        with:
          version: 'latest'
        id: install
      - name: Test
        working-directory: ./testing/helm
        run: ./run.sh
