roxie:
- name: roxie
  disabled: false
  prefix: roxie
  hpa:
    minReplicas: 3
    maxReplicas: 15
    metrics:
    - type: Resource
      name: "cpu"
      target: 
        type: Utilization
        value: "50"
    - type: Pods
      name: "packets-per-second"
      target:
        type: AverageValue
        value: "1k"
    - type: External
      name: queue_messages_ready
      selector:
        matchLabels:
          queue: "worker_tasks"
      target:
        type: AverageValue
        value: "30"
    - type: Object
      name: "requests-per-second"
      describedObject:
        apiVersion: api/v1
        kind: Pod
        name: certain-pod-of-service-B
      target:
        type: AverageValue
        value: "30"
  services:
  - name: roxie
    servicePort: 9876
    listenQueue: 200
    numThreads: 30
    visibility: local
    # Can override ingress rules for each service if desired - for example to add no additional ingress permissions you can use
    # ingress: []
  ## replicas indicates the number of replicas per channel
  replicas: 2
  numChannels: 2
  ## Set localAgent to true for a scalable cluster of "single-node" roxie servers, each implementing all channels locally
  localAgent: false
  ## Adjust traceLevel to taste (1 is default)
  traceLevel: 1
  ## set totalMemoryLimit to indicate how much memory is preallocated for roxie row data
  # totalMemoryLimit: "1Gi" # Default 1Gi, capped to 75% of resources.memory if defined.
  ## Set mtuPayload to the maximum amount of data Roxie will put in a single packet. This should be just less than the system MTU. Default is 1400
  # mtuPayload: 3800

  ## resources specifies the resources required by each agent pod
  #resources:
  #  cpu: "1"
  #  memory: "1G"

  ## Set serverReplicas to indicate a separate replicaSet of roxie servers, with agent pods not acting as servers
  serverReplicas: 0
  ## If serverReplicas is set, the resources required for the server pods can be configured separately from the agent (channel) pods
  #serverResources:
  #  cpu: "1"
  #  memory: "4Gi"
  #channelResources:
  #  cpu: "2"
  #  memory: "8Gi"

  # Roxie may take a while to start up if there are a lot of queries to load. Yuo may need to 
  #override the default startup/readiness probing by setting these values
  #minStartupTime: 30      # How long to wait before initiating startup probing
  #maxStartupTime: 600     # Maximum time to wait for startup to complete before failing
  topoServer:
    replicas: 1
  #directAccessPlanes: []  #add direct access planes that roxie will read from without copying the data to its default data plane
  #ldapUser: roxie_file_access    #add system username for accessing files
  #egress: engineEgress
